<div id="footerMainNoPatch" class="logoYes wYes">
 <div id="footerLeft">    	
  <ul>
   <li class="logoArea"><a href="http://www.washington.edu/">&#169; <!--chtml date="%Y"--> University of Washington</a></li>  
  </ul>
 </div>
 <div id="footerRight">  
  <ul>
   <li class="centerText"><a href="http://www.seattle.gov/">Seattle, Washington</a></li>
  </ul>   
 </div>
 <div id="footerCenter">
  <ul>
   <li><a href="http://www.washington.edu/home/siteinfo/form/">Contact Us</a></li>
   <li class="footerLinkBorder"><a href="http://www.washington.edu/jobs/">Jobs</a></li>
   <li class="footerLinkBorder"><a href="http://myuw.washington.edu/">My UW</a></li>
   <li class="footerLinkBorder"><a href="http://www.washington.edu/online/privacy">Privacy</a></li>
   <li class="footerLinkBorder"><a href="http://www.washington.edu/online/terms">Terms</a></li>
  </ul>
 </div>
</div>