<div id="footerMainNoPatch" class="logoYes wYes">
 <div id="footerLeft">    	
  <ul>
   <li class="logoArea"><a href="http://www.washington.edu/">&#169; 2009 University of Washington</a></li>  
  </ul>
 </div>
 <div id="footerRight">  
  <ul>
   <li class="centerText"><span>Seattle, Washington</span></li>
  </ul>   
 </div>
 <div id="footerCenter">
  <ul>
   <li><a href="http://www.washington.edu/home/siteinfo/form/">Contact Us</a></li>
   <li class="footerLinkBorder"><a href="http://www.washington.edu/jobs/">Employment</a></li>
   <li class="footerLinkBorder"><a href="http://myuw.washington.edu/">My UW</a></li>
  </ul>
 </div>
</div>