<div class="wheader colorGold  patchYes">
 <span id="autoMargin">

  <div class="wlogoSmall">
   <div class="logoAbsolute"><a id="wlogoLink" href="http://www.washington.edu/">W</a></div>
   <div><a href="http://www.washington.edu/">University of Washington</a></div>
  </div>
  <div id="wtext">
   <ul>
    <li><a href="http://www.washington.edu/">UW Home</a></li>

    <li><span class="border"><a href="http://www.washington.edu/home/directories.html">Directories</a></span></li>
    <li><span class="border"><a href="http://www.washington.edu/visit/events.html">Calendar</a></span></li>
    <li><span class="border"><a href="http://www.washington.edu/maps/">Maps</a></span></li>
    <li><span class="border"><a href="http://myuw.washington.edu/">My UW</a></span></li>
   </ul>
  </div>
 </span>

</div>
