<link rel="stylesheet" href="http://depts.washington.edu/uweb/inc/css/header.css" type="text/css" />
<link rel="stylesheet" href="http://depts.washington.edu/uweb/inc/css/footer.css" type="text/css" />
<link rel="stylesheet" href="http://depts.washington.edu/uweb/inc/css/print.css" type="text/css" media="print" />
<script type="text/javascript">
  // clear out the global search input text field
  function make_blank() {if(document.uwglobalsearch.q.value == "Search the UW") {document.uwglobalsearch.q.value = "";}}
</script>
