<div class="wheader colorGold patchYes">
 <span id="autoMargin">
  <div class="wlogoSmall">
   <div class="logoAbsolute"><a id="wlogoLink" href="http://www.washington.edu/">W</a></div>
   <div><a href="http://www.washington.edu/">University of Washington</a></div>
  </div>
  <div id="wsearch">        
   <form name="uwglobalsearch" id="searchbox_001967960132951597331:04hcho0_drk" action="http://www.google.com/cse">
    <div class="wfield">
     <input type="hidden" name="cx" value="001967960132951597331:04hcho0_drk" />
     <input type="hidden" name="cof" value="FORID:0" />
     <input name="q" type="text" value="Search the UW" class="wTextInput" onclick="make_blank();" />
    </div>   
    <input type="submit" class="formbutton" name="sa" value="Go" />
   </form>
  </div>
  <div id="wtext">
   <ul>
    <li><a href="http://www.washington.edu/">UW Home</a></li>
    <li><span class="wborder"><a href="http://www.washington.edu/home/directories.html">Directories</a></span></li>
    <li><span class="wborder"><a href="http://www.washington.edu/visit/events.html">Calendar</a></span></li>
    <li><span class="wborder"><a href="http://www.washington.edu/maps/">Maps</a></span></li>
    <li><span class="wborder"><a href="http://myuw.washington.edu/">My UW</a></span></li>
   </ul>
  </div>
 </span>
</div>